# Generated by Django 3.2.3 on 2021-06-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='visitor_id',
            new_name='visitor',
        ),
    ]
