# Generated by Django 3.2.3 on 2021-06-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20210602_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='description',
            field=models.CharField(default='TBC', max_length=500),
            preserve_default=False,
        ),
    ]
