# Generated by Django 3.2.3 on 2021-06-03 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
